---
- name: Run MySQL query on db servers
  hosts: db_servers
  become: false
  gather_facts: false
  tasks:
#    - name: Debug loaded variables for dbServer1
#      debug:
#        var: hostvars[inventory_hostname]

    - name: Run SQL Query on MySQL Server
      shell: >
        mysql -h {{ ansible_host }} -P {{ hostvars[inventory_hostname][inventory_hostname].mysql_port }} -u {{ hostvars[inventory_hostname][inventory_hostname].mysql_user }} -p'{{ hostvars[inventory_hostname][inventory_hostname].mysql_p>      register: query_result
      changed_when: false

    - name: Show SQL Query Result
      debug:
        var: query_result.stdout
